config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase if email.present? }
  before_save :format_name

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :email,
            presence: true,
  			    format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ },
  			    uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

  validates :password, presence: true, length: { minimum: 6 }, unless: :password_digest
  validates :password, length: { minimum: 6 }, allow_blank: true
  #validates :password_confirmation, presence: true

  has_secure_password

  def format_name
    # self.name = self.name.split.map{|name| name.capitalize}.join(' ') if name.present? # OK

    if name
      name_array =[]
      self.name.split.each do |n|
        name_array << n.capitalize
      end
      self.name = name_array.join(' ')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      create_session(user) # session[:user_id] = user.id
      #session[:user_id] = user.id
      flash[:notice] = "Welcome, #{user.name}!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    #session[:user_id] = nil
    # user = User.find(params[:id])
    # user = User.find_by(id: params[:user_id])
    # destroy_session(user)
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end

  # can't use strong params here because sessions does not have a model

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      create_session(@user) # signs in the user
      # session[:user_id] = @user.id    # same as above
      flash[:notice] = "User was saved successfully!"
      redirect_to root_url
    else
      flash[:error] = "There was an error saving. Please try again."
      render :new
    end
  end

  def confirm
    @user = User.new(user_params)
  end

  def edit
  #  @user = User.find(params[:id])
  end

  def update
  #  @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "You have updated your user account."
      redirect_to edit_user_path(@user)
    else
      flash[:error] = "There was a problem updating your account. Please try again."
      render :edit
    end
  end

  def destroy
  #  @user = User.find(params[:id])
    @user.destroy
    destroy_session(current_user) # session[:user_id] = nil
    flash[:notice] = "User is now deleted."
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag(:div, capture(&block), class: "form-group has-error")
    else
      content_tag(:div, capture(&block), class: "form-group")
    end
  end

  def flash_class(type)
    case type
      when "success" then "alert alert-success" # green
      when "info" then "alert alert-info"       # blue
      when "notice" then "alert alert-info"     # blue
      when "warning" then "alert alert-warning" # yellow
      when "alert" then "alert alert-warning"   # yellow
      when "danger" then "alert alert-danger"   # red
      when "error" then "alert alert-danger"    # red
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def create_session(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href= / >Authentication</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "about", about_path %></li>
      <li class="active"><a href="#">Link</a></li>
    </ul>

    <form class="navbar-form navbar-left" role="search">

    </form>

    <ul class="nav navbar-nav navbar-right">

      <% if current_user %>
        <li><%= link_to (current_user.name || current_user.email), edit_user_path(current_user) %></li>
        <li><%= link_to "Sign out", session_path(current_user), method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_session_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
      <% end %>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authenticate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <%= render 'layouts/navbar' %>
      <%= render partial: 'shared/flash_message' %>

      <%= yield %>

    </div>

  </body>
</html>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>

  <div class="row">
    <div class="col-md-6">
      <div class="well alert-danger">
      <h4><%= pluralize object.errors.count, "error" %></h4>
      <% object.errors.full_messages.each do |msg| %>
        <ul>
          <li><%= msg %></li>
        </ul>
      <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, msg| %>
  <div class="<%= flash_class(key) %>">
    <button type="button" class="close" data-dismiss="alert">&times;</button> 
    <%= msg %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6">

    <%= form_group_tag(@user.errors[:name]) do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter name", autofocus: true %>
    <% end %>

    <%= form_group_tag(@user.errors[:email]) do %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    <% end %>

    <%= form_group_tag(@user.errors[:password]) do %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    <% end %>

    <%= form_group_tag(@user.errors[:password_confirmation]) do %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password" %>
    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
    </div>

  </div>
</div>

app/views/users/confirm.html.erb
<h2>Sign Up Confirmation</h2>
<h4>Are you sure these values are correct?</h4>

<h4>
  Email: <%= @user.email %><br>
  Name: <%= @user.name %>
</h4>

<%= button_to "Yes", { controller: "users", action: "create", params: params.permit! }, class: "btn btn-success" %>
<%= button_to "No", { controller: "users", action: "new", params: params.permit! }, method: :get, class: "btn btn-danger confirmation-button-red" %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user, url: { action: :update } do |f| %>

  <%= render partial: 'shared/error_message', locals: { object: @user } %>

  <%= render partial: 'form', locals: { f: f } %>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user, url: { action: :confirm } do |f| %>

  <%= render partial: 'shared/error_message', locals: { object: @user } %>

  <%= render partial: 'form', locals: { f: f } %>

<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Authentication </h1>
  <p class="lead">This is a simple authentication example from scratch.</p>
  <hr class="my-4">
  <p>User authentication systems determine whether a user is who they claim to be. They allow users to sign up, sign in, and sign out. We'll build the app foundation using user authentication system by creating the User model.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>